var books = [
  {"bookNumber" : "1", "bookTitle" : " 1984 by George Orwell"},
  {"bookNumber" : "2", "bookTitle" : " Adventures of Huckleberry Finn by Mark Twain"},
  {"bookNumber" : "3", "bookTitle" : " Alice in Wonderland by Lewis Carroll"},
  {"bookNumber" : "4", "bookTitle" : " The Amazing Adventures of Kavalier &Clay by Michael Chabon"},
  {"bookNumber" : "5", "bookTitle" : " An American Tragedy by Theodore Dreiser"},
  {"bookNumber" : "6", "bookTitle" : " Angela’s Ashes by Frank McCourt"},
  {"bookNumber" : "7", "bookTitle" : " Anna Karenina by Leo Tolstoy"},
  {"bookNumber" : "8", "bookTitle" : " The Diary of a Young Girl by Anne Frank"},
  {"bookNumber" : "9", "bookTitle" : " The Archidamian War by Donald Kagan"},
  {"bookNumber" : "10", "bookTitle" : " The Art of Fiction by Henry James"},
  {"bookNumber" : "11", "bookTitle" : " The Art of War by Sun Tzu"},
  {"bookNumber" : "12", "bookTitle" : " As I Lay Dying by William Faulkner"},
  {"bookNumber" : "13", "bookTitle" : " Atonement by Ian McEwan"},
  {"bookNumber" : "14", "bookTitle" : " Autobiography of a Face by Lucy Grealy"},
  {"bookNumber" : "15", "bookTitle" : " The Awakening by Kate Chopin"},
  {"bookNumber" : "16", "bookTitle" : " Babe by Dick King-Smith"},
  {"bookNumber" : "17", "bookTitle" : " Backlash: The Undeclared War Against American Women by Susan Faludi"},
  {"bookNumber" : "18", "bookTitle" : " Balzac and the Little Chinese Seamstress by Dai Sijie"},
  {"bookNumber" : "19", "bookTitle" : " Bel Canto by Ann Patchett"},
  {"bookNumber" : "20", "bookTitle" : " The Bell Jar by Sylvia Plath"},
  {"bookNumber" : "21", "bookTitle" : " Beloved by Toni Morrison"},
  {"bookNumber" : "22", "bookTitle" : " Beowulf: A New Verse Translation by Seamus Heaney"},
  {"bookNumber" : "23", "bookTitle" : " The Bhagava Gita"},
  {"bookNumber" : "24", "bookTitle" : " The Bielski Brothers: The True Story of Three Men Who Defied the Nazis, Built a Village in the Forest, and Saved 1,200 Jews by Peter Duffy"},
  {"bookNumber" : "25", "bookTitle" : " Bitch in Praise of Difficult Women by Elizabeth Wurtzel"},
  {"bookNumber" : "26", "bookTitle" : " A Bolt from the Blue and Other Essays by Mary McCarthy"},
  {"bookNumber" : "27", "bookTitle" : " Brave New World by Aldous Huxley"},
  {"bookNumber" : "28", "bookTitle" : " Brick Lane by Monica Ali"},
  {"bookNumber" : "29", "bookTitle" : " Bridgadoon by Alan Jay Lerner"},
  {"bookNumber" : "30", "bookTitle" : " Candide by Voltaire"},
  {"bookNumber" : "31", "bookTitle" : " The Canterbury Tales by Chaucer"},
  {"bookNumber" : "32", "bookTitle" : " Carrie by Stephen King"},
  {"bookNumber" : "33", "bookTitle" : " Catch-22 by Joseph Heller"},
  {"bookNumber" : "34", "bookTitle" : " The Catcher in the Rye by J", "bookTitle" : " D", "bookTitle" : " Salinger"},
  {"bookNumber" : "35", "bookTitle" : " Charlotte’s Web by E", "bookTitle" : " B", "bookTitle" : " White"},
  {"bookNumber" : "36", "bookTitle" : " The Children’s Hour by Lillian Hellman"},
  {"bookNumber" : "37", "bookTitle" : " Christine by Stephen King"},
  {"bookNumber" : "38", "bookTitle" : " A Christmas Carol by Charles Dickens"},
  {"bookNumber" : "39", "bookTitle" : " A Clockwork Orange by Anthony Burgess"},
  {"bookNumber" : "40", "bookTitle" : " The Code of the Woosters by P.G", "bookTitle" : " Wodehouse"},
  {"bookNumber" : "41", "bookTitle" : " The Collected Stories by Eudora Welty"},
  {"bookNumber" : "42", "bookTitle" : " A Comedy of Errors by William Shakespeare"},
  {"bookNumber" : "43", "bookTitle" : " Complete Novels by Dawn Powell"},
  {"bookNumber" : "44", "bookTitle" : " The Complete Poems by Anne Sexton"},
  {"bookNumber" : "45", "bookTitle" : " Complete Stories by Dorothy Parker"},
  {"bookNumber" : "46", "bookTitle" : " A Confederacy of Dunces by John Kennedy Toole"},
  {"bookNumber" : "47", "bookTitle" : " The Count of Monte Cristo by Alexandre Dumas"},
  {"bookNumber" : "48", "bookTitle" : " Cousin Bette by Honore de Balzac"},
  {"bookNumber" : "49", "bookTitle" : " Crime and Punishment by Fyodor Dostoevsky"},
  {"bookNumber" : "50", "bookTitle" : " The Crimson Petal and the White by Michel Faber"},
  {"bookNumber" : "51", "bookTitle" : " The Crucible by Arthur Miller"},
  {"bookNumber" : "52", "bookTitle" : " Cujo by Stephen King"},
  {"bookNumber" : "53", "bookTitle" : " The Curious Incident of the Dog in the Night-Time by Mark Haddon"},
  {"bookNumber" : "54", "bookTitle" : " Daughter of Fortune by Isabel Allende"},
  {"bookNumber" : "55", "bookTitle" : " David and Lisa by Dr Theodore Issac Rubin M.D"},
  {"bookNumber" : "56", "bookTitle" : " David Copperfield by Charles Dickens"},
  {"bookNumber" : "57", "bookTitle" : " The Da Vinci -Code by Dan Brown"},
  {"bookNumber" : "58", "bookTitle" : " Dead Souls by Nikolai Gogol"},
  {"bookNumber" : "59", "bookTitle" : " Demons by Fyodor Dostoyevsky"},
  {"bookNumber" : "60", "bookTitle" : " Death of a Salesman by Arthur Miller"},
  {"bookNumber" : "61", "bookTitle" : " Deenie by Judy Blume"},
  {"bookNumber" : "62", "bookTitle" : " The Devil in the White City: Murder, Magic, and Madness at the Fair that Changed America by Erik Larson"},
  {"bookNumber" : "63", "bookTitle" : " The Dirt: Confessions of the World’s Most Notorious Rock Band by Tommy Lee, Vince Neil, Mick Mars and Nikki Sixx"},
  {"bookNumber" : "64", "bookTitle" : " The Divine Comedy by Dante"},
  {"bookNumber" : "65", "bookTitle" : " The Divine Secrets of the Ya-Ya Sisterhood by Rebecca Wells"},
  {"bookNumber" : "66", "bookTitle" : " Don Quixote by Cervantes"},
  {"bookNumber" : "67", "bookTitle" : " Driving Miss Daisy by Alfred Uhrv"},
  {"bookNumber" : "68", "bookTitle" : " Dr", "bookTitle" : " Jekyll &Mr", "bookTitle" : " Hyde by Robert Louis Stevenson"},
  {"bookNumber" : "69", "bookTitle" : " Edgar Allan Poe: Complete Tales &Poems by Edgar Allan Poe"},
  {"bookNumber" : "70", "bookTitle" : " Eleanor Roosevelt by Blanche Wiesen Cook"},
  {"bookNumber" : "71", "bookTitle" : " The Electric Kool-Aid Acid Test by Tom Wolfe"},
  {"bookNumber" : "72", "bookTitle" : " Ella Minnow Pea: A Novel in Letters by Mark Dunn"},
  {"bookNumber" : "73", "bookTitle" : " Eloise by Kay Thompson"},
  {"bookNumber" : "74", "bookTitle" : " Emily the Strange by Roger Reger"},
  {"bookNumber" : "75", "bookTitle" : " Emma by Jane Austen"},
  {"bookNumber" : "76", "bookTitle" : " Empire Falls by Richard Russo"},
  {"bookNumber" : "77", "bookTitle" : " Encyclopedia Brown: Boy Detective by Donald J", "bookTitle" : " Sobol"},
  {"bookNumber" : "78", "bookTitle" : " Ethan Frome by Edith Wharton"},
  {"bookNumber" : "79", "bookTitle" : " Ethics by Spinoza"},
  {"bookNumber" : "80", "bookTitle" : " Europe through the Back Door, 2003 by Rick Steves"},
  {"bookNumber" : "81", "bookTitle" : " Eva Luna by Isabel Allende"},
  {"bookNumber" : "82", "bookTitle" : " Everything Is Illuminated by Jonathan Safran Foer"},
  {"bookNumber" : "83", "bookTitle" : " Extravagance by Gary Krist"},
  {"bookNumber" : "84", "bookTitle" : " Fahrenheit 451 by Ray Bradbury"},
  {"bookNumber" : "85", "bookTitle" : " Fahrenheit 9/11 by Michael Moore"},
  {"bookNumber" : "86", "bookTitle" : " The Fall of the Athenian Empire by Donald Kagan"},
  {"bookNumber" : "87", "bookTitle" : " Fat Land: How Americans Became the Fattest People in the World by Greg Critser"},
  {"bookNumber" : "88", "bookTitle" : " Fear and Loathing in Las Vegas by Hunter S", "bookTitle" : " Thompson"},
  {"bookNumber" : "89", "bookTitle" : " The Fellowship of the Ring by JRR Tolkien"},
  {"bookNumber" : "90", "bookTitle" : " Fiddler on the Roof by Joseph Stein"},
  {"bookNumber" : "91", "bookTitle" : " The Five People You Meet in Heaven by Mitch Albom"},
  {"bookNumber" : "92", "bookTitle" : " Finnegan’s Wake by James Joyce"},
  {"bookNumber" : "93", "bookTitle" : " Fletch by Gregory McDonald"},
  {"bookNumber" : "94", "bookTitle" : " Flowers for Algernon by Daniel Keyes"},
  {"bookNumber" : "95", "bookTitle" : " The Fortress of Solitude by Jonathan Lethem"},
  {"bookNumber" : "96", "bookTitle" : " The Fountainhead by Ayn Rand"},
  {"bookNumber" : "97", "bookTitle" : " Frankenstein by Mary Shelley"},
  {"bookNumber" : "98", "bookTitle" : " Franny and Zooey by J", "bookTitle" : " D", "bookTitle" : " Salinger"},
  {"bookNumber" : "99", "bookTitle" : " Freaky Friday by Mary Rodgers"},
  {"bookNumber" : "100", "bookTitle" : " Galapagos by Kurt Vonnegut"},
  {"bookNumber" : "101", "bookTitle" : " Gender Trouble by Judith Butler"},
  {"bookNumber" : "102", "bookTitle" : " George W", "bookTitle" : " Bushism: The Slate Book of the Accidental Wit and Wisdom of our 43rd President by Jacob Weisberg"},
  {"bookNumber" : "103", "bookTitle" : " Gidget by Fredrick Kohner"},
  {"bookNumber" : "104", "bookTitle" : " Girl, Interrupted by Susanna Kaysen"},
  {"bookNumber" : "105", "bookTitle" : " The Gnostic Gospels by Elaine Pagels"},
  {"bookNumber" : "106", "bookTitle" : " The Godfather: Book 1 by Mario Puzo"},
  {"bookNumber" : "107", "bookTitle" : " The God of Small Things by Arundhati Roy"},
  {"bookNumber" : "108", "bookTitle" : " Goldilocks and the Three Bears by Alvin Granowsky"},
  {"bookNumber" : "109", "bookTitle" : " Gone with the Wind by Margaret Mitchell"},
  {"bookNumber" : "110", "bookTitle" : " The Good Soldier by Ford Maddox Ford"},
  {"bookNumber" : "111", "bookTitle" : " The Gospel According to Judy Bloom"},
  {"bookNumber" : "112", "bookTitle" : " The Graduate by Charles Webb"},
  {"bookNumber" : "113", "bookTitle" : " The Grapes of Wrath by John Steinbeck"},
  {"bookNumber" : "114", "bookTitle" : " The Great Gatsby by F", "bookTitle" : " Scott Fitzgerald"},
  {"bookNumber" : "115", "bookTitle" : " Great Expectations by Charles Dickens"},
  {"bookNumber" : "116", "bookTitle" : " The Group by Mary McCarthy"},
  {"bookNumber" : "117", "bookTitle" : " Hamlet by William Shakespeare"},
  {"bookNumber" : "118", "bookTitle" : " Harry Potter and the Goblet of Fire by JK Rowling"},
  {"bookNumber" : "119", "bookTitle" : " Harry Potter and the Sorcerer’s Stone by JK Rowling"},
  {"bookNumber" : "120", "bookTitle" : " A Heartbreaking Work of Staggering Genius by Dave Eggers"},
  {"bookNumber" : "121", "bookTitle" : " Heart of Darkness by Joseph Conrad"},
  {"bookNumber" : "122", "bookTitle" : " Helter Skelter: The True Story of the Manson Murders by Vincent Bugliosi and Curt Gentry"},
  {"bookNumber" : "123", "bookTitle" : " Henry IV, part I by William Shakespeare"},
  {"bookNumber" : "124", "bookTitle" : " Henry IV, part II by William Shakespeare"},
  {"bookNumber" : "125", "bookTitle" : " Henry V by William Shakespeare"},
  {"bookNumber" : "126", "bookTitle" : " High Fidelity by Nick Hornby"},
  {"bookNumber" : "127", "bookTitle" : " The History of the Decline and Fall of the Roman Empire by Edward Gibbon"},
  {"bookNumber" : "128", "bookTitle" : " Holidays on Ice: Stories by David Sedaris"},
  {"bookNumber" : "129", "bookTitle" : " The Holy Barbarians by Lawrence Lipton"},
  {"bookNumber" : "130", "bookTitle" : " House of Sand and Fog by Andre Dubus III"},
  {"bookNumber" : "131", "bookTitle" : " The House of the Spirits by Isabel Allende"},
  {"bookNumber" : "132", "bookTitle" : " How to Breathe Underwater by Julie Orringer"},
  {"bookNumber" : "133", "bookTitle" : " How the Grinch Stole Christmas by Dr Seuss"},
  {"bookNumber" : "134", "bookTitle" : " How the Light Gets In by MJ Hyland"},
  {"bookNumber" : "135", "bookTitle" : " Howl by Allen Ginsberg"},
  {"bookNumber" : "136", "bookTitle" : " The Hunchback of Notre Dame by Victor Hugo"},
  {"bookNumber" : "137", "bookTitle" : " The Iliad by Homer"},
  {"bookNumber" : "138", "bookTitle" : " I’m With the Band by Pamela des Barres"},
  {"bookNumber" : "139", "bookTitle" : " In Cold Blood by Truman Capote"},
  {"bookNumber" : "140", "bookTitle" : " Inferno by Dante"},
  {"bookNumber" : "141", "bookTitle" : " Inherit the Wind by Jerome Lawrence and Robert E Lee"},
  {"bookNumber" : "142", "bookTitle" : " Iron Weed by William J Kennedy"},
  {"bookNumber" : "143", "bookTitle" : " It Takes a Village by Hillary Rodham Clinton"},
  {"bookNumber" : "144", "bookTitle" : " Jane Eyre by Charlotte Bronte"},
  {"bookNumber" : "145", "bookTitle" : " The Joy Luck Club by Amy Tan"},
  {"bookNumber" : "146", "bookTitle" : " Julius Caesar by William Shakespeare"},
  {"bookNumber" : "147", "bookTitle" : " The Jumping Frog by Mark Twain"},
  {"bookNumber" : "148", "bookTitle" : " The Jungle by Upton Sinclair"},
  {"bookNumber" : "149", "bookTitle" : " Just a Couple of Days by Tony Vigorito"},
  {"bookNumber" : "150", "bookTitle" : " The Kitchen Boy: A Novel of the Last Tsar by Robert Alexander"},
  {"bookNumber" : "151", "bookTitle" : " Kitchen Confidential: Adventures in the Culinary Underbelly by Anthony Bourdain"},
  {"bookNumber" : "152", "bookTitle" : " The Kite Runner by Khaled Hosseini"},
  {"bookNumber" : "153", "bookTitle" : " Lady Chatterleys’ Lover by DH Lawrence"},
  {"bookNumber" : "154", "bookTitle" : " The Last Empire: Essays 1992-2000 by Gore Vidal"},
  {"bookNumber" : "155", "bookTitle" : " Leaves of Grass by Walt Whitman"},
  {"bookNumber" : "156", "bookTitle" : " The Legend of Bagger Vance by Steven Pressfield"},
  {"bookNumber" : "157", "bookTitle" : " Less Than Zero by Bret Easton Ellis"},
  {"bookNumber" : "158", "bookTitle" : " Letters to a Young Poet by Rainer Maria Rilke"},
  {"bookNumber" : "159", "bookTitle" : " Lies and the Lying Liars Who Tell Them by Al Franken"},
  {"bookNumber" : "160", "bookTitle" : " Life of Pi by Yann Martel"},
  {"bookNumber" : "161", "bookTitle" : " Little Dorrit by Charles Dickens"},
  {"bookNumber" : "162", "bookTitle" : " The Little Locksmith by Katharine Butler Hathaway"},
  {"bookNumber" : "163", "bookTitle" : " The Little Match Girl by Hans Christian Andersen"},
  {"bookNumber" : "164", "bookTitle" : " Little Women by Louisa May Alcott"},
  {"bookNumber" : "165", "bookTitle" : " Living History by Hillary Rodham Clinton"},
  {"bookNumber" : "166", "bookTitle" : " Lord of the Flies by William Golding"},
  {"bookNumber" : "167", "bookTitle" : " The Lottery: And Other Stories by Shirley Jackson"},
  {"bookNumber" : "168", "bookTitle" : " The Lovely Bones by Alice Sebold"},
  {"bookNumber" : "169", "bookTitle" : " The Love Story by Erich Segal"},
  {"bookNumber" : "170", "bookTitle" : " Macbeth by William Shakespeare"},
  {"bookNumber" : "171", "bookTitle" : " Madame Bovary by Gustave Flaubert"},
  {"bookNumber" : "172", "bookTitle" : " The Manticore by Robertson Davies"},
  {"bookNumber" : "173", "bookTitle" : " Marathon Man by William Goldman"},
  {"bookNumber" : "174", "bookTitle" : " The Master and Margarita by Mikhail Bulgakov"},
  {"bookNumber" : "175", "bookTitle" : " Memoirs of a Dutiful Daughter by Simone de Beauvoir"},
  {"bookNumber" : "176", "bookTitle" : " Memoirs of General W", "bookTitle" : " T", "bookTitle" : " Sherman by William Tecumseh Sherman"},
  {"bookNumber" : "177", "bookTitle" : " Me Talk Pretty One Day by David Sedaris"},
  {"bookNumber" : "178", "bookTitle" : " The Meaning of Consuelo by Judith Ortiz Cofer"},
  {"bookNumber" : "179", "bookTitle" : " Mencken’s Chrestomathy by HR Mencken"},
  {"bookNumber" : "180", "bookTitle" : " The Merry Wives of Windsor by William Shakespeare"},
  {"bookNumber" : "181", "bookTitle" : " The Metamorphosis by Franz Kafka"},
  {"bookNumber" : "182", "bookTitle" : " Middlesex by Jeffrey Eugenides"},
  {"bookNumber" : "183", "bookTitle" : " The Miracle Worker by William Gibson"},
  {"bookNumber" : "184", "bookTitle" : " Moby Dick by Herman Melville"},
  {"bookNumber" : "185", "bookTitle" : " The Mojo Collection: The Ultimate Music Companion by Jim Irvin"},
  {"bookNumber" : "186", "bookTitle" : " Moliere: A Biography by Hobart Chatfield Taylor"},
  {"bookNumber" : "187", "bookTitle" : " A Monetary History of the United States by Milton Friedman"},
  {"bookNumber" : "188", "bookTitle" : " Monsieur Proust by Celeste Albaret"},
  {"bookNumber" : "189", "bookTitle" : " A Month Of Sundays: Searching For The Spirit And My Sister by Julie Mars"},
  {"bookNumber" : "190", "bookTitle" : " A Moveable Feast by Ernest Hemingway"},
  {"bookNumber" : "191", "bookTitle" : " Mrs", "bookTitle" : " Dalloway by Virginia Woolf"},
  {"bookNumber" : "192", "bookTitle" : " Mutiny on the Bounty by Charles Nordhoff and James Norman Hall"},
  {"bookNumber" : "193", "bookTitle" : " My Lai 4: A Report on the Massacre and It’s Aftermath by Seymour M Hersh"},
  {"bookNumber" : "194", "bookTitle" : " My Life as Author and Editor by HR Mencken"},
  {"bookNumber" : "195", "bookTitle" : " My Life in Orange: Growing Up with the Guru by Tim Guest"},
  {"bookNumber" : "196", "bookTitle" : " Myra Waldo’s Travel and Motoring Guide to Europe, 1978 by Myra Waldo"},
  {"bookNumber" : "197", "bookTitle" : " My Sister’s Keeper by Jodi Picoult"},
  {"bookNumber" : "198", "bookTitle" : " The Naked and the Dead by Norman Mailer"},
  {"bookNumber" : "199", "bookTitle" : " The Name of the Rose by Umberto Eco"},
  {"bookNumber" : "200", "bookTitle" : " The Namesake by Jhumpa Lahiri"},
  {"bookNumber" : "201", "bookTitle" : " The Nanny Diaries by Emma McLaughlin"},
  {"bookNumber" : "202", "bookTitle" : " Nervous System: Or, Losing My Mind in Literature by Jan Lars Jensen"},
  {"bookNumber" : "203", "bookTitle" : " New Poems of Emily Dickinson by Emily Dickinson"},
  {"bookNumber" : "204", "bookTitle" : " The New Way Things Work by David Macaulay"},
  {"bookNumber" : "205", "bookTitle" : " Nickel and Dimed by Barbara Ehrenreich"},
  {"bookNumber" : "206", "bookTitle" : " Night by Elie Wiesel"},
  {"bookNumber" : "207", "bookTitle" : " Northanger Abbey by Jane Austen"},
  {"bookNumber" : "208", "bookTitle" : " The Norton Anthology of Theory and Criticism by William E. Cain, Laurie A. Finke, Barbara E. Johnson, John P. McGowan"},
  {"bookNumber" : "209", "bookTitle" : " Novels 1930-1942: Dance Night/Come Back to Sorrento, Turn, Magic Wheel/Angels on Toast/A Time to be Born by Dawn Powell"},
  {"bookNumber" : "210", "bookTitle" : " Notes of a Dirty Old Man by Charles Bukowski"},
  {"bookNumber" : "211", "bookTitle" : " Of Mice and Men by John Steinbeck"},
  {"bookNumber" : "212", "bookTitle" : " Old School by Tobias Wolff"},
  {"bookNumber" : "213", "bookTitle" : " On the Road by Jack Kerouac"},
  {"bookNumber" : "214", "bookTitle" : " One Flew Over the Cuckoo’s Nest by Ken Kesey"},
  {"bookNumber" : "215", "bookTitle" : " One Hundred Years of Solitude by Gabriel Garcia Marquez"},
  {"bookNumber" : "216", "bookTitle" : " The Opposite of Fate: Memories of a Writing Life by Amy Tan"},
  {"bookNumber" : "217", "bookTitle" : " Oracle Night by Paul Auster"},
  {"bookNumber" : "218", "bookTitle" : " Oryx and Crake by Margaret Atwood"},
  {"bookNumber" : "219", "bookTitle" : " Othello by Shakespeare"},
  {"bookNumber" : "220", "bookTitle" : " Our Mutual Friend by Charles Dickens"},
  {"bookNumber" : "221", "bookTitle" : " The Outbreak of the Peloponnesian War by Donald Kagan"},
  {"bookNumber" : "222", "bookTitle" : " Out of Africa by Isac Dineson"},
  {"bookNumber" : "223", "bookTitle" : " The Outsiders by SE Hinton"},
  {"bookNumber" : "224", "bookTitle" : " A Passage to India by E.M", "bookTitle" : " Forster"},
  {"bookNumber" : "225", "bookTitle" : " The Peace of Nicias and the Sicilian Expedition by Donald Kagan"},
  {"bookNumber" : "226", "bookTitle" : " The Perks of Being a Wallflower by Stephen Chbosky"},
  {"bookNumber" : "227", "bookTitle" : " Peyton Place by Grace Metalious"},
  {"bookNumber" : "228", "bookTitle" : " The Picture of Dorian Gray by Oscar Wilde"},
  {"bookNumber" : "229", "bookTitle" : " Pigs at the Trough by Arianna Huffington"},
  {"bookNumber" : "230", "bookTitle" : " Pinocchio by Carlo Collodi"},
  {"bookNumber" : "231", "bookTitle" : " Please Kill Me: The Uncensored Oral History of Punk Legs McNeil and Gillian McCain"},
  {"bookNumber" : "232", "bookTitle" : " The Polysyllabic Spree by Nick Hornby"},
  {"bookNumber" : "233", "bookTitle" : " The Portable Dorothy Parker by Dorothy Parker"},
  {"bookNumber" : "234", "bookTitle" : " The Portable Nietzche by Fredrich Nietzche"},
  {"bookNumber" : "235", "bookTitle" : " The Price of Loyalty: George W", "bookTitle" : " Bush, the White House, and the Education of Paul O’Neill by Ron Suskind"},
  {"bookNumber" : "236", "bookTitle" : " Pride and Prejudice by Jane Austen"},
  {"bookNumber" : "237", "bookTitle" : " Property by Valerie Martin"},
  {"bookNumber" : "238", "bookTitle" : " Pushkin: A Biography by TJ Binyon"},
  {"bookNumber" : "239", "bookTitle" : " Pygmalion by George Bernard Shaw"},
  {"bookNumber" : "240", "bookTitle" : " Quattrocento by James Mckean"},
  {"bookNumber" : "241", "bookTitle" : " A Quiet Storm by Rachel Howzell Hall"},
  {"bookNumber" : "242", "bookTitle" : " Rapunzel by Grimm Brothers"},
  {"bookNumber" : "243", "bookTitle" : " The Raven by Edgar Allan Poe"},
  {"bookNumber" : "244", "bookTitle" : " The Razor’s Edge by W", "bookTitle" : " Somerset Maugham"},
  {"bookNumber" : "245", "bookTitle" : " Reading Lolita in Tehran: A Memoir in Books by Azar Nafisi"},
  {"bookNumber" : "246", "bookTitle" : " Rebecca by Daphne du Maurier"},
  {"bookNumber" : "247", "bookTitle" : " Rebecca of Sunnybrook Farm by Kate Douglas Wiggin"},
  {"bookNumber" : "248", "bookTitle" : " The Red Tent by Anita Diamant"},
  {"bookNumber" : "249", "bookTitle" : " Rescuing Patty Hearst: Memories From a Decade Gone Mad by Virginia Holman"},
  {"bookNumber" : "250", "bookTitle" : " The Return of the King by JRR Tolkien"},
  {"bookNumber" : "251", "bookTitle" : " R Is for Ricochet by Sue Grafton"},
  {"bookNumber" : "252", "bookTitle" : " Rita Hayworth by Stephen King"},
  {"bookNumber" : "253", "bookTitle" : " Robert’s Rules of Order by Henry Robert"},
  {"bookNumber" : "254", "bookTitle" : " Roman Holiday by Edith Wharton"},
  {"bookNumber" : "255", "bookTitle" : " Romeo and Juliet by William Shakespeare"},
  {"bookNumber" : "256", "bookTitle" : " A Room of One’s Own by Virginia Woolf"},
  {"bookNumber" : "257", "bookTitle" : " A Room with a View by E", "bookTitle" : " M", "bookTitle" : " Forster"},
  {"bookNumber" : "258", "bookTitle" : " Rosemary’s Baby by Ira Levin"},
  {"bookNumber" : "259", "bookTitle" : " The Rough Guide to Europe, 2003 Edition"},
  {"bookNumber" : "260", "bookTitle" : " Sacred Time by Ursula Hegi"},
  {"bookNumber" : "261", "bookTitle" : " Sanctuary by William Faulkner"},
  {"bookNumber" : "262", "bookTitle" : " Savage Beauty: The Life of Edna St", "bookTitle" : " Vincent Millay by Nancy Milford"},
  {"bookNumber" : "263", "bookTitle" : " Say Goodbye to Daisy Miller by Henry James"},
  {"bookNumber" : "264", "bookTitle" : " The Scarecrow of Oz by Frank L", "bookTitle" : " Baum"},
  {"bookNumber" : "265", "bookTitle" : " The Scarlet Letter by Nathaniel Hawthorne"},
  {"bookNumber" : "266", "bookTitle" : " Seabiscuit: An American Legend by Laura Hillenbrand"},
  {"bookNumber" : "267", "bookTitle" : " The Second Sex by Simone de Beauvoir"},
  {"bookNumber" : "268", "bookTitle" : " The Secret Life of Bees by Sue Monk Kidd"},
  {"bookNumber" : "269", "bookTitle" : " Secrets of the Flesh: A Life of Colette by Judith Thurman"},
  {"bookNumber" : "270", "bookTitle" : " Selected Hotels of Europe"},
  {"bookNumber" : "271", "bookTitle" : " Selected Letters of Dawn Powell: 1913-1965 by Dawn Powell"},
  {"bookNumber" : "272", "bookTitle" : " Sense and Sensibility by Jane Austen"},
  {"bookNumber" : "273", "bookTitle" : " A Separate Peace by John Knowles"},
  {"bookNumber" : "274", "bookTitle" : " Several Biographies of Winston Churchill"},
  {"bookNumber" : "275", "bookTitle" : " Sexus by Henry Miller"},
  {"bookNumber" : "276", "bookTitle" : " The Shadow of the Wind by Carlos Ruiz Zafon"},
  {"bookNumber" : "277", "bookTitle" : " Shane by Jack Shaefer"},
  {"bookNumber" : "278", "bookTitle" : " The Shining by Stephen King"},
  {"bookNumber" : "279", "bookTitle" : " Siddhartha by Hermann Hesse"},
  {"bookNumber" : "280", "bookTitle" : " S Is for Silence by Sue Grafton"},
  {"bookNumber" : "281", "bookTitle" : " Slaughter-house Five by Kurt Vonnegut"},
  {"bookNumber" : "282", "bookTitle" : " Small Island by Andrea Levy"},
  {"bookNumber" : "283", "bookTitle" : " Snows of Kilimanjaro by Ernest Hemingway"},
  {"bookNumber" : "284", "bookTitle" : " Snow White and Rose Red by Grimm Brothers"},
  {"bookNumber" : "285", "bookTitle" : " Social Origins of Dictatorship and Democracy: Lord and Peasant in the Making of the Modern World by Barrington Moore"},
  {"bookNumber" : "286", "bookTitle" : " The Song of Names by Norman Lebrecht"},
  {"bookNumber" : "287", "bookTitle" : " Song of the Simple Truth: The Complete Poems of Julia de Burgos by Julia de Burgos"},
  {"bookNumber" : "288", "bookTitle" : " The Song Reader by Lisa Tucker"},
  {"bookNumber" : "289", "bookTitle" : " Songbook by Nick Hornby"},
  {"bookNumber" : "290", "bookTitle" : " The Sonnets by William Shakespeare"},
  {"bookNumber" : "291", "bookTitle" : " Sonnets from the Portuegese by Elizabeth Barrett Browning"},
  {"bookNumber" : "292", "bookTitle" : " Sophie’s Choice by William Styron"},
  {"bookNumber" : "293", "bookTitle" : " The Sound and the Fury by William Faulkner"},
  {"bookNumber" : "294", "bookTitle" : " Speak, Memory by Vladimir Nabokov"},
  {"bookNumber" : "295", "bookTitle" : " Stiff: The Curious Lives of Human Cadavers by Mary Roach"},
  {"bookNumber" : "296", "bookTitle" : " The Story of My Life by Helen Keller"},
  {"bookNumber" : "297", "bookTitle" : " A Streetcar Named Desiree by Tennessee Williams"},
  {"bookNumber" : "298", "bookTitle" : " Stuart Little by EB White"},
  {"bookNumber" : "299", "bookTitle" : " Sun Also Rises by Ernest Hemingway"},
  {"bookNumber" : "300", "bookTitle" : " Swann’s Way by Marcel Proust"},
  {"bookNumber" : "301", "bookTitle" : " Swimming with Giants: My Encounters with Whales, Dolphins and Seals by Anne Collett"},
  {"bookNumber" : "302", "bookTitle" : " Sybil by Flora Rheta Schreiber"},
  {"bookNumber" : "303", "bookTitle" : " A Tale of Two Cities by Charles Dickens"},
  {"bookNumber" : "304", "bookTitle" : " Tender Is The Night by F", "bookTitle" : " Scott Fitzgerald"},
  {"bookNumber" : "305", "bookTitle" : " Term of Endearment by Larry McMurtry"},
  {"bookNumber" : "306", "bookTitle" : " Time and Again by Jack Finney"},
  {"bookNumber" : "307", "bookTitle" : " The Time Traveler’s Wife by Audrey Niffenegger"},
  {"bookNumber" : "308", "bookTitle" : " To Have and Have Not by Ernest Hemingway"},
  {"bookNumber" : "309", "bookTitle" : " To Kill a Mockingbird by Harper Lee"},
  {"bookNumber" : "310", "bookTitle" : " The Tragedy of Richard III by William Shakespeare"},
  {"bookNumber" : "311", "bookTitle" : " A Tree Grows in Brooklyn by Betty Smith"},
  {"bookNumber" : "312", "bookTitle" : " The Trial by Franz Kafka"},
  {"bookNumber" : "313", "bookTitle" : " The True and Outstanding Adventures of the Hunt Sisters by Elisabeth Robinson"},
  {"bookNumber" : "314", "bookTitle" : " Truth &Beauty: A Friendship by Ann Patchett"},
  {"bookNumber" : "315", "bookTitle" : " Tuesdays with Morrie by Mitch Albom"},
  {"bookNumber" : "316", "bookTitle" : " Ulysses by James Joyce"},
  {"bookNumber" : "317", "bookTitle" : " The Unabridged Journals of Sylvia Plath 1950-1962 by Sylvia Plath"},
  {"bookNumber" : "318", "bookTitle" : " Uncle Tom’s Cabin by Harriet Beecher Stowe"},
  {"bookNumber" : "319", "bookTitle" : " Unless by Carol Shields"},
  {"bookNumber" : "320", "bookTitle" : " Valley of the Dolls by Jacqueline Susann"},
  {"bookNumber" : "321", "bookTitle" : " The Vanishing Newspaper by Philip Meyers"},
  {"bookNumber" : "322", "bookTitle" : " Vanity Fair by William Makepeace Thackeray"},
  {"bookNumber" : "323", "bookTitle" : " Velvet Underground’s The Velvet Underground and Nico (Thirty Three and a Third series) by Joe Harvard"},
  {"bookNumber" : "324", "bookTitle" : " The Virgin Suicides by Jeffrey Eugenides"},
  {"bookNumber" : "325", "bookTitle" : " Waiting for Godot by Samuel Beckett"},
  {"bookNumber" : "326", "bookTitle" : " Walden by Henry David Thoreau"},
  {"bookNumber" : "327", "bookTitle" : " Walt Disney’s Bambi by Felix Salten"},
  {"bookNumber" : "328", "bookTitle" : " War and Peace by Leo Tolstoy"},
  {"bookNumber" : "329", "bookTitle" : " We Owe You Nothing – Punk Planet: The Collected Interviews edited by Daniel Sinker"},
  {"bookNumber" : "330", "bookTitle" : " What Colour is Your Parachute? 2005 by Richard Nelson Bolles"},
  {"bookNumber" : "331", "bookTitle" : " What Happened to Baby Jane by Henry Farrell"},
  {"bookNumber" : "332", "bookTitle" : " When the Emperor Was Divine by Julie Otsuka"},
  {"bookNumber" : "333", "bookTitle" : " Who Moved My Cheese? by Spencer Johnson"},
  {"bookNumber" : "334", "bookTitle" : " Who’s Afraid of Virginia Woolf by Edward Albee"},
  {"bookNumber" : "335", "bookTitle" : " Wicked: The Life and Times of the Wicked Witch of the West by Gregory Maguire"},
  {"bookNumber" : "336", "bookTitle" : " The Wizard of Oz by Frank L", "bookTitle" : " Baum"},
  {"bookNumber" : "337", "bookTitle" : " Wuthering Heights by Emily Bronte"},
  {"bookNumber" : "338", "bookTitle" : " The Yearling by Marjorie Kinnan Rawlings"},
  {"bookNumber" : "339", "bookTitle" : " The Year of Magical Thinking by Joan Didion"}
];


document.addEventListener('DOMContentLoaded', function () {
  // console.log(books.length);
  var rand = Math.floor(Math.random() * books.length);
  // console.log(rand);
  window.onload = function(){
  	document.getElementById("chosenBook").innerHTML =  books[rand]['bookTitle'];
  	// document.getElementById("myquote").innerHTML = stupid[rand]['quote'];
    //   document.getElementById("occupation").innerHTML = stupid[rand]['occupation'];
  }

  // $(document).ready(function() {
  //     $("body").css("background-color", "hsla(" + Math.floor(Math.random() * (360)) + ", 75%, 58%, 1)");
  // });



	q = "gilmore girls"; // search query

	request = new XMLHttpRequest;
	request.open('GET', 'http://api.giphy.com/v1/gifs/random?api_key=dc6zaTOxFJmzC&tag='+q, true);

	request.onload = function() {
		if (request.status >= 200 && request.status < 400){
			data = JSON.parse(request.responseText).data.image_url;
			console.log(data);
			document.getElementById("giphyme").innerHTML = '<center><img src = "'+data+'"  title="GIF via Giphy"></center>';
		} else {
			console.log('reached giphy, but API returned an error');
      document.getElementById("giphyme").innerHTML = '<center><img src = "cynic.gif"  title="GIF via Giphy"></center>';
		 }
	};

	request.onerror = function() {
		console.log('connection error');
	};

	request.send();
});
